// This file is automatically generated. Do not modify it manually.
// You can publish a new configuration by running `firebase apps:sdkconfig web`
// and copying the output to this file.

export const firebaseConfig = {
  "projectId": "studio-2894162921-ba253",
  "appId": "1:856866736814:web:cd15d4bfab11744ccc3b3f",
  "storageBucket": "studio-2894162921-ba253.appspot.com",
  "apiKey": "AIzaSyBAkOgEjw79KbhUUnixKlSdUYp6n_wcwd4",
  "authDomain": "studio-2894162921-ba253.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "856866736814"
};
